import json,re
from pathlib import Path
P=Path('research/deep-research-i-and-love-and-you.json'); d=json.loads(P.read_text()); assert len(d['records'])==183
by={r['upc']:r for r in d['records']}
U=['818336013614','818336013621','818336013706','818336012242','818336010361','818336010378']
def valid(s):
 ds=list(map(int,s)); return (sum(ds[-2::-2])*3+sum(ds[-3::-2])+ds[-1])%10==0
assert all(valid(x) and x not in by for x in U)
# global duplicate gate outside owned ledger
for f in list(Path('research').glob('deep-research-*.json'))+[Path('data/known-products.ts'),Path('data/known-formulas.ts'),Path('data/wrong-barcodes.ts'),Path('docs/CATALOG-CONFLICTS.md')]:
 if f==P or not f.exists(): continue
 t=f.read_text(errors='ignore')
 for u in U: assert u not in t,(u,str(f))

def rec(upc,species,name,variant,life,form,texture,pres,pkg,size,ingredients,ga,cal,formula,urls,notes,recipe=None,scope='individual_unit',children=None,line=None):
 return {'catalog_number':None,'upc':upc,'canonical_gtin14':upc.zfill(14),'barcode_scope':scope,'multipack_contents':children or [],'brand':'I and love and you','manufacturer':'NatPets LLC / I and love and you','species':species,'product_line':line,'product_name':name,'variant':variant,'recipe':recipe or [variant],'life_stage':life,'food_form':form,'texture':texture,'presentation':pres,'package_type':pkg,'size':size,'ingredients_verbatim':ingredients,'ingredients_ordered_normalized':[x.strip() for x in ingredients.split(',')],'guaranteed_analysis':ga,'calorie_content':cal,'label_deck_code':None,'formula_source':formula,'source_urls':urls,'source_accessed_at':'2026-08-29','barcode_notes':'UPC-A check digit independently validated.','conflicts':[],'verification_notes':notes+['UPC-A check digit validated; canonical GTIN-14 is zero-left-padded UPC-A.'],'research_status':'source_verified'}

def GA(p,f,fi,m,t=None,other=[]): return {'crude_protein_min_percent':p,'crude_fat_min_percent':f,'crude_fiber_max_percent':fi,'moisture_max_percent':m,'ash_max_percent':None,'taurine_min_percent':t,'other_printed_guarantees':other}
chicken='CHICKEN BROTH, CHICKEN, DRIED EGG PRODUCT, TUNA, TAPIOCA STARCH, TRICALCIUM PHOSPHATE, SALT, GUAR GUM, MINERALS (ZINC OXIDE, REDUCED IRON, SODIUM SELENITE, MANGANESE SULFATE, COPPER AMINO ACID COMPLEX, POTASSIUM IODIDE), POTASSIUM CHLORIDE, MAGNESIUM SULFATE, TAURINE, VITAMINS (VITAMIN E SUPPLEMENT, NIACIN SUPPLEMENT, THIAMINE MONONITRATE, VITAMIN A SUPPLEMENT, VITAMIN B12 SUPPLEMENT, PYRIDOXINE HYDROCHLORIDE, D-CALCIUM PANTOTHENATE, RIBOFLAVIN SUPPLEMENT, BIOTIN, VITAMIN D3 SUPPLEMENT, FOLIC ACID, MENADIONE SODIUM BISULFITE COMPLEX (SOURCE OF VITAMIN K ACTIVITY)), CHOLINE CHLORIDE.'
tuna='FISH BROTH, TUNA, DRIED EGG PRODUCT, TAPIOCA STARCH, SUNFLOWER OIL, TRICALCIUM PHOSPHATE, SALT, GUAR GUM, MINERALS (ZINC OXIDE, REDUCED IRON, SODIUM SELENITE, MANGANESE SULFATE, COPPER AMINO ACID COMPLEX, POTASSIUM IODIDE), POTASSIUM CHLORIDE, MAGNESIUM SULFATE, TAURINE, VITAMINS (VITAMIN E SUPPLEMENT, NIACIN SUPPLEMENT, THIAMINE MONONITRATE, VITAMIN A SUPPLEMENT, VITAMIN B12 SUPPLEMENT, PYRIDOXINE HYDROCHLORIDE, D-CALCIUM PANTOTHENATE, RIBOFLAVIN SUPPLEMENT, BIOTIN, VITAMIN D3 SUPPLEMENT, FOLIC ACID, MENADIONE SODIUM BISULFITE COMPLEX (SOURCE OF VITAMIN K ACTIVITY)), CHOLINE CHLORIDE.'
M='https://iandloveandyou.com/products/xoxo-chicken-tuna-stew-variety-pack'
UNFI='https://img1.wsimg.com/blobby/go/aa7b10cd-c46b-4154-9e6a-5baa0913363d/UNFI%2520jan_jun%25202025.pdf'
rows=[]
rows.append(rec(U[0],'cat','XOXOs Chicken & Tuna Stew','Chicken & Tuna Stew','all','wet','stew','can','can','3 oz',chicken,GA(7.5,3.0,1.5,82.0,0.07),{'kcal_per_kg':1046,'kcal_per_unit':88,'unit_name':'can'},'Current manufacturer XOXOs variety page supplies the exact component formula/GA/calories and AAFCO growth-and-maintenance statement; 2025 UNFI catalog independently maps UPC 818336013614 to XOXOs Chicken & Tuna Stew, 24/3 OZ.',[M,UNFI],['Manufacturer formula is component-specific and matches the exact Chicken & Tuna Stew identity; distributor catalog proves the 3 oz sellable-unit UPC.'],['chicken','tuna'],line='XOXOs'))
rows.append(rec(U[1],'cat','XOXOs Tuna & Egg Stew','Tuna & Egg Stew','all','wet','stew','can','can','3 oz',tuna,GA(7.5,2.5,1.5,82.0,0.07),{'kcal_per_kg':938,'kcal_per_unit':79,'unit_name':'can'},'Current manufacturer XOXOs variety page supplies exact Tuna & Egg component formula/GA/calories and AAFCO growth-and-maintenance statement; 2025 UNFI catalog maps UPC 818336013621 to XOXOs Tuna & Egg Stew, 24/3 OZ.',[M,UNFI],['Manufacturer formula is component-specific and distributor catalog proves the 3 oz sellable-unit UPC.'],['tuna','egg'],line='XOXOs'))
# Feed Meow variety outer pack
FM='https://iandloveandyou.com/products/feed-meow-variety-pack'; TH='https://thrivemarket.com/p/i-and-love-and-you-feed-meow-variety-pack'
child=[]
for u,n in [('818336013645','Feed Meow Boost Chicken Feast'),('818336013669','Feed Meow Tummy Tuna with Pumpkin Feast'),('818336013652','Feed Meow Shine Salmon & Tuna Feast')]:
 assert u in by
 child.append({'upc':None,'canonical_gtin14':None,'standalone_upc':u,'product_name':n,'size':'3 oz pouch','quantity':4,'evidence_status':'matched_standalone_sku','source_urls':[FM]+by[u].get('source_urls',[])})
fm_ing='Feed Meow Tummy Tuna with Pumpkin Feast: '+by['818336013669']['ingredients_verbatim']+' Feed Meow Boost Chicken Feast: '+by['818336013645']['ingredients_verbatim']+' Feed Meow Shine Salmon & Tuna Feast: '+by['818336013652']['ingredients_verbatim']
rows.append(rec(U[2],'cat','Feed Meow Variety Pack','3 OZ (12 PACK)','all','wet',None,'pouch','box','12 x 3 oz pouches',fm_ing,GA(None,None,1.5,84.0,0.05),{'kcal_per_kg':None,'kcal_per_unit':None,'unit_name':None},'Current manufacturer page proves 12-pack composition (4 Boost + 4 Tummy + 4 Shine), each component formula/GA/calories, and complete-and-balanced adequacy; Thrive Market and package-backed retailer evidence map UPC 818336013706 to the 12-pouch pack.',[FM,TH,'https://hibid.com/florida/lot/247850038/-i-and-love-and-you--cat-wet-food-variety-pack'],['Component protein/fat/calories differ, so no invented aggregate pack value is stored; component values remain traceable through the three separately source-verified standalone records and manufacturer page.'],['chicken','tuna','pumpkin','salmon'],scope='multipack',children=child,line='Feed Meow'))
# Hip Hoppin historical treat
hip='Chicken, ground yellow peas, tapioca starch, coconut glycerin, dried ground garbanzo beans, dried sweet potatoes, pea fiber, pork gelatin, flaxseed meal, lactic acid, natural smoke flavor, glucosamine hydrochloride, chicken fat, dried cultured skim milk, magnesium sulfate, mixed tocopherols (preservative), rosemary extract, green tea extract, turmeric powder'
rows.append(rec(U[3],'dog',"Hip Hoppin' Hearties",'Chicken','all','treat',None,'bite','bag','5 oz',hip,GA(11.0,7.0,7.0,18.0,None,[{'nutrient':'Glucosamine HCl per treat','basis':'min','value':14,'unit':'other'},{'nutrient':'Glucosamine HCl per treat','basis':'max','value':22,'unit':'other'}]),{'kcal_per_kg':3100,'kcal_per_unit':5,'unit_name':'piece'},'Archived retailer label transcription provides exact ingredients, GA, calories and UPC for the discontinued 5 oz Chicken treat.', ['https://www.maxwarehouse.com/es/products/i-and-love-and-you-dog-trt-hip-hop-heart-chk-case-of-6-5-oz-pack-of-6','https://sosuplementos.com.br/produto/i-and-love-and-you-hip-hoppin-hearties-chicken-5-oz/'],['Historical/discontinued SKU; retained as a verified label generation rather than mixed with current products.'],['chicken'],line="Hip Hoppin' Hearties"))
# Historical 5.5lb dehydrated generations
beef='Beef, Sweet Potatoes, Yellow Split Peas, Carrots, Dried Egg Product, Flaxseeds, Cabbage, Bananas, Tricalcium Phosphate, Dried Kelp, Spinach, Ginger Root, Zinc Sulfate, Vitamin E supplement, Ferrous Fumarate, Copper Sulfate, d Calcium Pantothenate, Riboflavin, Vitamin D3 Supplement, Pyridoxine Hydrochloride, Folic Acid.'
rows.append(rec(U[4],'dog','In The Raw Beef Recipe / Raw Raw Beef Boom Ba','Beef Recipe 5.5 lb historical generation','all','dry',None,'dehydrated','bag','5.5 lb',beef,GA(28.0,15.0,5.0,10.0,None,[{'nutrient':'Omega 6','basis':'min','value':1.8,'unit':'percent'},{'nutrient':'Omega 3','basis':'min','value':0.5,'unit':'percent'}]),{'kcal_per_kg':3702,'kcal_per_unit':351,'unit_name':'cup'},'Sprouts proves UPC 818336010361 and exact 5.5 lb identity; archived Chewy 5.5-lb page preserves that historical formula generation, GA and calories. Current manufacturer formula differs and is intentionally not substituted.', ['https://shop.sprouts.com/store/sprouts/products/135909-i-and-love-and-you-stir-boom-raw-raw-beef-boom-ba-5-5-lb','https://www.chewy.com/i-love-you-stir-boom-raw-raw-beef/dp/117046'],['Historical 5.5 lb formula generation. Current manufacturer Raw Raw Beef formula has changed (3391 kcal/kg, 22% protein); generation conflict is resolved by using the archived exact-size Chewy formula for this UPC.'],['beef'],line='In The Raw / Stir & Boom'))
chick='Chicken, Sweet Potatoes, Yellow Split Peas, Carrots, Cabbage, Dried Egg Product, Flaxseeds, Bananas, Tricalcium Phosphate, Dried Kelp, Spinach, Ginger Root, Zinc Sulfate, Vitamin E supplement, Ferrous Fumarate, Copper Sulfate, d Calcium Pantothenate, Riboflavin, Vitamin D3 Supplement, Pyridoxine Hydrochloride, Folic Acid.'
rows.append(rec(U[5],'dog','In The Raw Chicken Recipe / Raw Raw Chick Boom Ba','Chicken Recipe 5.5 lb historical generation','all','dry',None,'dehydrated','bag','5.5 lb',chick,GA(32.0,10.0,4.0,10.0,None,[{'nutrient':'Omega 6','basis':'min','value':1.75,'unit':'percent'},{'nutrient':'Omega 3','basis':'min','value':6.0,'unit':'percent'}]),{'kcal_per_kg':3455,'kcal_per_unit':327,'unit_name':'cup'},'Max Warehouse proves UPC 818336010378 and exact 5.5 lb historical Chicken identity; archived Chewy exact-size page supplies ingredients, GA and calories for that generation.', ['https://www.maxwarehouse.com/products/i-and-love-and-you-dog-dehydrated-food-in-the-raw-chicken-recipe-case-of-3-5-5-lb-pack-of-3','https://www.chewy.com/i-love-you-stir-boom-raw-raw-chick/dp/117038'],['Historical/discontinued 5.5 lb formula generation; exact-size archived formula used and not mixed with newer current recipe.'],['chicken'],line='In The Raw / Stir & Boom'))
d['records'].extend(rows); d['updated_at']='2026-08-29'
assert len(d['records'])==189 and sum(r.get('research_status')=='source_verified' for r in d['records'])==189
P.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
print('ILY_184_189_OK before=183 added=6 total=189 source_verified=189')
print('ADDED',','.join(U))
