import json,copy
from pathlib import Path
ROOT=Path('.'); LED=ROOT/'research/deep-research-i-and-love-and-you.json'; TODAY='2026-08-29'
data=json.loads(LED.read_text()); assert len(data['records'])==160,len(data['records']); by={r['upc']:r for r in data['records']}
ex=''
for p in [ROOT/'data/known-products.ts',ROOT/'data/known-formulas.ts',ROOT/'data/wrong-barcodes.ts',ROOT/'docs/CATALOG-CONFLICTS.md']+list((ROOT/'research').glob('deep-research-*.json')):
 if p!=LED and p.exists(): ex+=p.read_text(errors='ignore')+'\n'
def ok(s):
 ds=list(map(int,s)); total=sum(d*(3 if i%2==0 else 1) for i,d in enumerate(reversed(ds[:-1]))); return s.isdigit() and len(s) in (12,13,14) and (10-total%10)%10==ds[-1]
def base_record(upc,barcode,name,variant,url,species='cat',form='wet',ptype='box'):
 r=copy.deepcopy(by[upc]); r['catalog_number']=None; r['upc']=barcode; r['canonical_gtin14']=barcode.zfill(14); r['barcode_scope']='multipack'; r['product_name']=name; r['variant']=variant; r['size']=variant; r['package_type']=ptype; r['source_urls']=list(dict.fromkeys([url,url+'.js']+list(r.get('source_urls') or []))); r['source_accessed_at']=TODAY; r['barcode_notes']=f'Current manufacturer Shopify .js maps outer barcode {barcode} exactly to {variant}; this is the retail multipack barcode, not an inner-unit UPC.'; r['verification_notes']=list(r.get('verification_notes') or [])+[f'2026-08-29: current manufacturer product page and Shopify variant prove outer barcode {barcode} = {variant}.']; r['research_status']='source_verified'; return r
def variety(barcode,name,variant,url,children,quantities):
 r=base_record(children[0],barcode,name,variant,url,by[children[0]]['species'])
 r['recipe']=[by[x]['variant'] for x in children]
 r['ingredients_verbatim']=' | '.join(f"{by[x]['product_name']}: {by[x]['ingredients_verbatim']}" for x in children)
 r['ingredients_ordered_normalized']=[f"{by[x]['product_name']}: "+' > '.join(by[x]['ingredients_ordered_normalized']) for x in children]
 r['guaranteed_analysis']={'crude_protein_min_percent':None,'crude_fat_min_percent':None,'crude_fiber_max_percent':None,'moisture_max_percent':None,'ash_max_percent':None,'taurine_min_percent':None,'other_printed_guarantees':[]}
 r['calorie_content']={'kcal_per_kg':None,'kcal_per_unit':None,'unit_name':None}
 r['component_guaranteed_analyses']=[{'product_name':by[x]['product_name'],'guaranteed_analysis':by[x]['guaranteed_analysis'],'calorie_content':by[x]['calorie_content']} for x in children]
 r['multipack_contents']=[{'standalone_upc':x,'canonical_gtin14':by[x]['canonical_gtin14'],'product_name':by[x]['product_name'],'size':by[x]['size'],'quantity':q,'evidence_status':'matched_standalone_sku','source_urls':by[x]['source_urls']} for x,q in zip(children,quantities)]
 r['formula_source']='Current manufacturer variety-pack page plus source-verified component records in this ledger; component formulas and analyses are preserved separately because the outer pack contains multiple recipes.'
 r['verification_notes'].append('Outer variety pack contains multiple formulas; complete component ingredient statements, analyses, and calories are captured in ingredients_verbatim/component_guaranteed_analyses rather than collapsed into false single values.')
 return r
def explicit(barcode,name,variant,url,template,ingredients,norm,ga,kcal,life='all',recipe=None):
 r=base_record(template,barcode,name,variant,url,by[template]['species']); r['ingredients_verbatim']=ingredients; r['ingredients_ordered_normalized']=norm; r['guaranteed_analysis']=ga; r['calorie_content']=kcal; r['life_stage']=life; r['recipe']=recipe or [name]; r['formula_source']='Current manufacturer product page for exact recipe; current Shopify .js variant for exact outer barcode and pack size.'; return r
new=[]
# Feed Meow Zen 12/24
zen_ing='Fish Broth, Sardine, Tuna, Turkey, Tapioca Starch, Sunflower Oil, Inulin, Tricalcium Phosphate, Guar Gum, L-Tryptophan, Minerals (Zinc Oxide, Reduced Iron, Sodium Selenite, Manganese Sulfate Monohydrate, Copper Amino Acid Complex, Potassium Iodide), Taurine, Vitamins (Vitamin E Supplement, Vitamin A Supplement, Niacin Supplement, Thiamine Mononitrate, Pyridoxine Hydrochloride, Vitamin D3 Supplement, D-Calcium Pantothenate, Riboflavin Supplement, Biotin, Vitamin B12 Supplement, Folic Acid, Menadione Sodium Bisulfite Complex (Source Of Vitamin K Activity)), Choline Chloride, Potassium Chloride, Sodium Tripolyphosphate.'
zen_norm=['Fish Broth','Sardine','Tuna','Turkey','Tapioca Starch','Sunflower Oil','Inulin','Tricalcium Phosphate','Guar Gum','L-Tryptophan','Minerals (Zinc Oxide, Reduced Iron, Sodium Selenite, Manganese Sulfate Monohydrate, Copper Amino Acid Complex, Potassium Iodide)','Taurine','Vitamins (Vitamin E Supplement, Vitamin A Supplement, Niacin Supplement, Thiamine Mononitrate, Pyridoxine Hydrochloride, Vitamin D3 Supplement, D-Calcium Pantothenate, Riboflavin Supplement, Biotin, Vitamin B12 Supplement, Folic Acid, Menadione Sodium Bisulfite Complex (Source Of Vitamin K Activity))','Choline Chloride','Potassium Chloride','Sodium Tripolyphosphate']
zen_ga={'crude_protein_min_percent':12.0,'crude_fat_min_percent':1.5,'crude_fiber_max_percent':1.0,'moisture_max_percent':85.0,'ash_max_percent':None,'taurine_min_percent':0.05,'other_printed_guarantees':[{'nutrient':'Tryptophan (Calculated)','basis':'min','value':0.09,'unit':'percent'}]}
for b,v,q in [('818336013874','3 OZ (12 PACK)',12),('818336013881','3 OZ (24 PACK)',24)]:
 r=explicit(b,'Feed Meow Zen Sardine & Tuna Feast',v,'https://iandloveandyou.com/products/feed-meow-zen-sardine-tuna-feast','818336013645',zen_ing,zen_norm,zen_ga,{'kcal_per_kg':716,'kcal_per_unit':60,'unit_name':'pouch'},'all',['Sardine','Tuna']); r['multipack_contents']=[{'standalone_upc':None,'canonical_gtin14':None,'product_name':'Feed Meow Zen Sardine & Tuna Feast','size':'3 oz pouch','quantity':q,'evidence_status':'unit_not_for_individual_sale','source_urls':[r['source_urls'][0]]}]; new.append(r)
# XOXO current variety packs
new += [variety('10818336013567','XOXOs Chicken & Beef Pâté Variety Pack','3 OZ CAN (24 PACK)','https://iandloveandyou.com/products/xoxo-chicken-beef-pate-variety-pack',['818336013591','818336013607'],[12,12]),variety('818336013560','XOXOs Chicken & Beef Pâté Variety Pack','3 OZ (12 PACK)','https://iandloveandyou.com/products/xoxo-chicken-beef-pate-variety-pack',['818336013591','818336013607'],[6,6]),variety('818336013546','XOXOs Salmon & Whitefish Pâté Variety Pack','3 OZ (12 PACK)','https://iandloveandyou.com/products/xoxo-salmon-whitefish-pate-variety-pack',['818336013584','818336013577'],[6,6])]
# Treat Meow variety 12/48 using the three verified puree component SKUs
new += [variety('818336013867','TREAT MEOW VARIETY PACK - 12CT','12 PACK','https://iandloveandyou.com/products/treat-meow-variety-pack',['818336013843','818336012112','818336013829'],[4,4,4]),variety('10818336013864','TREAT MEOW VARIETY PACK - 48CT','48 PACK','https://iandloveandyou.com/products/treat-meow-variety-pack',['818336013843','818336012112','818336013829'],[16,16,16])]
# Irresist-A-Bowls exact current formulas
cb_ing='CHICKEN, CARROTS, PUMPKIN, BEEF, PEAS, SALT, WATER SUFFICIENT FOR PROCESSING, DRIED SPINACH, MINERALS (ZINC OXIDE, REDUCED IRON, MANGANESE SULFATE, COPPER AMINO ACID COMPLEX, POTASSIUM IODIDE), VITAMINS (VITAMIN E SUPPLEMENT, VITAMIN B12 SUPPLEMENT, VITAMIN A SUPPLEMENT, NIACIN, d-CALCIUM PANTOTHENATE, THIAMINE MONONITRATE, BIOTIN, RIBOFLAVIN SUPPLEMENT, PYRIDOXINE HYDROCHLORIDE, VITAMIN D3 SUPPLEMENT, BETA-CAROTENE, FOLIC ACID), CHICORY PULP, POTASSIUM CHLORIDE, MAGNESIUM SULFATE, CHOLINE CHLORIDE.'
cd_ing=cb_ing.replace('BEEF','DUCK')
def split_ir(s): return ['CHICKEN','CARROTS','PUMPKIN',('DUCK' if 'DUCK' in s else 'BEEF'),'PEAS','SALT','WATER SUFFICIENT FOR PROCESSING','DRIED SPINACH','MINERALS (ZINC OXIDE, REDUCED IRON, MANGANESE SULFATE, COPPER AMINO ACID COMPLEX, POTASSIUM IODIDE)','VITAMINS (VITAMIN E SUPPLEMENT, VITAMIN B12 SUPPLEMENT, VITAMIN A SUPPLEMENT, NIACIN, d-CALCIUM PANTOTHENATE, THIAMINE MONONITRATE, BIOTIN, RIBOFLAVIN SUPPLEMENT, PYRIDOXINE HYDROCHLORIDE, VITAMIN D3 SUPPLEMENT, BETA-CAROTENE, FOLIC ACID)','CHICORY PULP','POTASSIUM CHLORIDE','MAGNESIUM SULFATE','CHOLINE CHLORIDE']
ga_ir={'crude_protein_min_percent':10.0,'crude_fat_min_percent':5.5,'crude_fiber_max_percent':3.0,'moisture_max_percent':77.0,'ash_max_percent':None,'taurine_min_percent':None,'other_printed_guarantees':[]}
for b,v,ing,kcal,url,recipe in [('818336013751','9 OZ (4 PACK)',cd_ing,(1513,385),'https://iandloveandyou.com/products/irresist-a-bowls-chicken-duck-recipe-1',['Chicken','Duck']),('10818336013758','9 OZ (8 PACK)',cd_ing,(1513,385),'https://iandloveandyou.com/products/irresist-a-bowls-chicken-duck-recipe-1',['Chicken','Duck']),('818336013775','9 OZ (4 PACK)',cb_ing,(1506,384),'https://iandloveandyou.com/products/irresist-a-bowls-chicken-beef-recipe',['Chicken','Beef']),('10818336013772','9 OZ (8 PACK)',cb_ing,(1506,384),'https://iandloveandyou.com/products/irresist-a-bowls-chicken-beef-recipe',['Chicken','Beef'])]:
 r=explicit(b,'Irresist-A-Bowls - '+('Chicken & Duck Recipe' if 'DUCK' in ing else 'Chicken & Beef Recipe'),v,url,'818336010170',ing,split_ir(ing),ga_ir,{'kcal_per_kg':kcal[0],'kcal_per_unit':kcal[1],'unit_name':'pouch'},'adult',recipe); r['species']='dog'; r['product_line']='Irresist-A-Bowls'; r['food_form']='wet'; r['texture']=None; r['presentation']='plain'; r['multipack_contents']=[{'standalone_upc':None,'canonical_gtin14':None,'product_name':r['product_name'],'size':'9 oz pouch','quantity':4 if '4 PACK' in v else 8,'evidence_status':'unit_not_for_individual_sale','source_urls':[url]}]; new.append(r)
# Dog variety packs: formulas already source-verified in component records
new += [variety('818336012334','Dog Can Variety-Pack - Flew The Coop','13 OZ CAN (6 PACK)','https://iandloveandyou.com/products/dog-can-variety-pack-stew-cluckin-good-stew-gobble-it-up-stew',['818336010194','818336010187'],[3,3]),variety('20818336012338','Dog Can Variety-Pack - Flew The Coop','13 OZ (12 PACK)','https://iandloveandyou.com/products/dog-can-variety-pack-stew-cluckin-good-stew-gobble-it-up-stew',['818336010194','818336010187'],[6,6]),variety('818336012327','Dog Can Variety Pack, Stew - Double Dog Deer Moo','13 OZ CAN (6 PACK)','https://iandloveandyou.com/products/dog-can-variety-pack-stew-beef-booyah-stew-moo-moo-venison-stew',['818336010170','818336011962'],[3,3]),variety('20818336012321','Dog Can Variety Pack, Stew - Double Dog Deer Moo','13 oz (12 PACK)','https://iandloveandyou.com/products/dog-can-variety-pack-stew-beef-booyah-stew-moo-moo-venison-stew',['818336010170','818336011962'],[6,6])]
# Lambarama homogeneous 12-pack, current manufacturer exact formula
lam_ing='Lamb, Lamb Broth, Vegetable Broth, Beef Liver, Carrots, Dried Egg Whites, Dried Peas, Sweet Potatoes, Guar Gum, Salt, Dicalcium Phosphate, Green Beans, Sunflower Oil, Sodium Phosphate, Natural Flavor, Potassium Chloride, Pumpkin, Choline Chloride, Cranberries, Zinc Proteinate, Iron Proteinate, Calcium Carbonate, Magnesium Sulfate, Salmon Oil (Preserved With Mixed Tocopherols), Vitamin E Supplement, Copper Proteinate, Cobalt Proteinate, Manganese Proteinate, Sodium Selenite, Thiamine Mononitrate, Niacin Supplement, d-Calcium Pantothenate, Riboflavin Supplement, Vitamin D3 Supplement, Biotin, Vitamin B12 Supplement, Potassium Iodide, Vitamin A Supplement, Pyridoxine Hydrochloride, Folic Acid.'
lam_norm=[x.strip() for x in lam_ing[:-1].split(', ')]
lam=explicit('10818336011976','Lambarama Stew','13 OZ CAN (12 PACK)','https://iandloveandyou.com/products/wet-canned-stew-dog-food-lambarama-stew','818336010170',lam_ing,lam_norm,{'crude_protein_min_percent':8.0,'crude_fat_min_percent':5.0,'crude_fiber_max_percent':1.0,'moisture_max_percent':82.0,'ash_max_percent':None,'taurine_min_percent':None,'other_printed_guarantees':[]},{'kcal_per_kg':987,'kcal_per_unit':364,'unit_name':'can'},'all',['Lamb']); lam['species']='dog'; lam['product_line']='Original Recipe'; lam['multipack_contents']=[{'standalone_upc':None,'canonical_gtin14':None,'product_name':'Lambarama Stew','size':'13 oz can','quantity':12,'evidence_status':'unit_not_for_individual_sale','source_urls':[lam['source_urls'][0]]}]; new.append(lam)
# Beef + Lamb dog variety packs use Lambarama formula captured above
by['10818336011976']=lam
new += [variety('818336012341','Dog Can Variety-Pack, Stew - Bad Mooooon On The Rise','13 OZ CAN (6 PACK)','https://iandloveandyou.com/products/dog-can-variety-pack-stew-beef-booyah-stew-lambarama-stew',['818336010170','10818336011976'],[3,3]),variety('20818336012345','Dog Can Variety-Pack, Stew - Bad Mooooon On The Rise','13 OZ (12 PACK)','https://iandloveandyou.com/products/dog-can-variety-pack-stew-beef-booyah-stew-lambarama-stew',['818336010170','10818336011976'],[6,6])]
# Pate All Day current 12/48 packs
new += [variety('818336011764','Original Recipe - Cat Can Variety Pack - Pâté All Day','3 OZ CAN (12 PACK)','https://iandloveandyou.com/products/wet-canned-cat-food-variety-pack-pate-all-day',['818336010231','818336011689','818336010224'],[4,4,4]),variety('10818336011761','Original Recipe - Cat Can Variety Pack - Pâté All Day','3oz (48 PACK)','https://iandloveandyou.com/products/wet-canned-cat-food-variety-pack-pate-all-day',['818336010231','818336011689','818336010224'],[16,16,16])]
assert len(new)==20,len(new); codes=[r['upc'] for r in new]; assert len(set(codes))==20
for r in new:
 assert ok(r['upc']),r['upc']; assert r['upc'] not in {x['upc'] for x in data['records']}; assert r['upc'] not in ex,r['upc']; assert r['ingredients_verbatim']; assert r['ingredients_ordered_normalized']; assert r['source_urls']; assert r['research_status']=='source_verified'
data['records'].extend(new); data['updated_at']=TODAY
allc=[r['upc'] for r in data['records']]; assert len(allc)==180 and len(allc)==len(set(allc)); assert sum(r.get('research_status')=='source_verified' for r in data['records'])==180
LED.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
print('ILY_161_180_OK before=160 added=20 total=180 source_verified=180')
print('ADDED',','.join(codes))
