import json,urllib.request
handles=['dog-chew-treats-nice-jerky-chicken-salmon','fillin-good-chicken-flavor-with-immune-support','fillin-good-seafood-flavor-with-immune-support','fillin-good-salmon-flavor-with-skin-coat-support','treat-meow-digestion-support','treat-meow-immune-support','treat-meow-skin-coat-support','dog-meal-enhancers-top-that-tummy-chicken-recipe','dog-meal-enhancers-top-that-shine-beef-recipe','dog-meal-enhancers-top-that-boost-duck-recipe','top-that-move-beef-with-bison-recipe-in-gravy','top-that-thrive-turkey-september-2025','top-that-wit-lamb-recipe-in-gravy','top-that-gaze-salmon-recipe-in-gravy','irresist-a-bowls-chicken-duck-recipe-1','irresist-a-bowls-chicken-beef-recipe','wet-canned-cat-food-purrky-turkey-pate','wet-canned-cat-food-savory-salmon-pate','wet-canned-cat-food-oh-my-cod-pate','wet-canned-cat-food-chicken-me-out-pate','wet-canned-cat-food-beef-right-meow-pate','wet-canned-cat-food-whascally-wabbit-pate','wet-canned-cat-food-salmon-chanted-evening-stew','wet-canned-cat-food-tuna-fintastic-stew','wet-canned-cat-food-chicky-da-lish-stew','xoxo-chicken-beef-pate-variety-pack','xoxo-salmon-whitefish-pate-variety-pack','xoxo-chicken-tuna-stew-variety-pack','feed-meow-variety-pack','treat-meow-variety-pack','wet-canned-cat-food-variety-pack-pate-all-day','wet-canned-cat-food-variety-pack-ninja-cat-jiu-jit-stew','wet-canned-cat-food-variety-pack-farm-to-sea','dog-can-variety-pack-stew-cluckin-good-stew-gobble-it-up-stew','dog-can-variety-pack-stew-beef-booyah-stew-moo-moo-venison-stew','dog-can-variety-pack-stew-beef-booyah-stew-lambarama-stew']
def getj(h):
 req=urllib.request.Request('https://iandloveandyou.com/products/'+h+'.js',headers={'User-Agent':'Mozilla/5.0'})
 with urllib.request.urlopen(req,timeout=30) as r:return json.loads(r.read().decode())
for h in handles:
 try:
  d=getj(h); print('HANDLE',h); print(json.dumps([{'title':v.get('title'),'barcode':v.get('barcode'),'sku':v.get('sku'),'available':v.get('available')} for v in d.get('variants',[])],ensure_ascii=False))
 except Exception as e: print('FAIL',h,e)
